### ISSUE TITLE
Official status of this repository is unclear

### ISSUE THREAD

**Issue by jbweston** [dmtx/libdmtx#18]
In the README there is a link to www.libdmtx.org, which now points to a web page about German powertools. There are also links to an old wiki, a repository on sourceforge, and some company's website that does not even load, in my browser.

I also notice that the [Debian packages](https://tracker.debian.org/pkg/libdmtx) pull from the (AFAICT defunct) sourceforge repository, however the [Brew packages](https://formulae.brew.sh/formula/libdmtx) do use *this* Github repo.

@msva what is the status of this GitHub fork; are you in contact with the original authors?

If this is now the official libdmtx repo, maybe we could clean up the README a bit to reflect this.

**Comment by msva** [comment]
> @msva what is the status of this GitHub fork; are you in contact with the
> original authors?

I contacted the authors (well, Mike Laughton actually) before making the 
organization on github and "forking" the repos from SF.

I'll post our conversation at the end.


> If this is now the official libdmtx repo, maybe we could clean up the README
> a bit to reflect this.

Well, I can't pretend on "officiality" of this repo (especially, with the 
squatted domain) or either on "official inheritance", but, at least, it is 
only ACKed "alive" fork for sure ☺.


--

Here's our discussion with Mike:


> 25.09.2012 0:38:01 MSK Mike Laughton wrote:
>
> No problem at all. Let me know if you need anything.
> 
> On Mon, Sep 17, 2012 at 11:57 PM, Vadim A. Misbakh-Soloviov wrote:
>
> > So, don't you have any objections if I try to add temporary fork on
> > GitHub and implement some things from TODO, and, possibly, Lua wrapper? ;)
> > 
> > 18.09.2012 11:53 MSK, Mike Laughton wrote:
> > > Hi Vadim,
> > > 
> > > Unfortunately I haven't had any time to work on or support the project
> > > for over a year, and I don't see the situation changing anytime soon. I
> > > wouldn't say the project is dead, but it's certainly not being actively
> > > maintained right now.
> > > 
> > > I hope this helps,
> > > Mike
> > > 
> > > 
> > > On Sat, Sep 15, 2012 at 5:38 AM, Vadim A. Misbakh-Soloviov wrote:
> > >
> > > > Hi, Mike!
> > > > Can you tell me, what is the current libdmtx/dmtx-utils/dmtx-wrappers
> > > > status?
> > > > As far as I see — the have no updates for about year atm. Does project
> > > > still alive?
> > > > --
> > > > Best,
> > > > mva

**Comment by jbweston** [comment]
OK, thanks for the clarification.

I will open a ticket with the Debian package maintainer and ask him to consider pulling from this repository in the future.

Would you accept merge requests that clean up the places in the documentation that point to defunct resources?

**Comment by msva** [comment]
> Would you accept merge requests that clean up the places in the
> documentation that point to defunct resources?

Ok, sure.

**Comment by jbweston** [comment]
The Debian package maintainer got back to me, so now the Debian packages will pull
from this repository.

Here's the email correspondence, for completeness:

> Hi Joseph,
> 
> No problem, I'll work on a new release.
> Thank you for your mail!
> 
> Regards,
> Roberto
> 
> On Wed, Aug 8, 2018 at 3:15 PM, Joseph Weston wrote:
> 
>     Dear Mr. Lumbreras,
> 
>     I am a user of the Debian libdmtx* packages, and I would like to request
>     that the upstream source code be obtained from the repository hosted on
>     GitHub: https://github.com/dmtx/libdmtx, rather than from (the now
>     defunct) http://www.libdmtx.org.
> 
>     The libdmtx.org domain has now been squatted and no longer has anything
>     to do with the data matrix library.
> 
>     In addition the original authors have essentially abandoned the project,
>     however they have unofficially handed the reigns to Vadim A.
>     Misbakh-Soloviov (GitHub username "msva"), as evidenced by the following
>     discussion thread: https://github.com/dmtx/libdmtx/issues/18.
> 
>     There was an upstream patch release (0.7.5), and it would be good if the
>     Debian packages could stay abreast of this and further upstream releases.
> 
> 
>     Regards,
> 
>     Joseph
> 
>

**Comment by jbweston** [comment]
It seems that this library is pre-v1.0, and  it seems to have been that way for a long time.

I see a list of TODOs in the project root, however I'm not sure what the status of all this is.

@msva are you actively developing this project, or acting mainly in a maintainer role? I'd like to get involved more but I'm not sure what your vision is (and I don't want to open PRs proposing sweeping changes that aren't necessarily wanted). Thanks!

**Comment by msva** [comment]
I'm acting mostly as maintainer.
Some time ago I fixed some annoying things, but since then I have almost no time to develop something (I have some "far from being finished" local branches with working on mosaic, on charsets and so on, but, as I said, I rarely have enough time to work on all of that.

So, at the moment, I mostly review and merge PRs (again, if I'm not very busy at work or with family).

Also, I've no objections about inviting you in the project/organisation, if you want to help me with maintenance and development.

**Comment by mblaughton** [comment]
Hi everyone,

After noticing the activity around this github repo I realized that my old libdmtx resources floating around the web might be causing confusion for potential users.

I have changed the status of the original libdmtx project on Sourceforge from "abandoned" to "moved" and tagged it with https://github.com/dmtx as the replacement URL.

I also updated the old libdmtx.org content (now hosted at http://libdmtx.sourceforge.net/) to point users to this github repo, or alternatively I could take down that site entirely if someone would like it removed.

I also remembered the old wiki that I set up to try and help with the support load at http://libdmtx.wikidot.com/. I was tempted to just remove it all, but I'm not sure if anyone finds it useful. I'll leave it undisturbed unless I hear any requests to do otherwise.

Thanks for picking up this project and keeping it alive. I still don't have any time to contribute, but it's fun to know that people still find it useful after all these years!

**Comment by nieder** [comment]
What is the status of libdmtx DOT org domain? It still points to a site about german power tools. [This project](https://github.com/dmtx) has a link there at the very top. If that domain has been taken by someone else, presumably the link should be removed?

**Comment by msva** [comment]
Domain is still squatted.

But issue that GH organization points to is is fixed now.
